
spring:
  application:
    name: risk-engine-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Updated to JsonSerializer for your Drools objects
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Updated to JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Important: Allow Spring to trust your model package for deserialization
        spring.json.trusted.packages: "com.riskengine.model"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs